name: REIGNTAKEOVER
favicon: null
layout_spectrum: 0.37184
typography_spectrum: 0.2336242003366351
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#0036c7'
    - '#898989'
    - '#fd0030'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
