name: REIGNTAKEOVER
favicon: null
layout_spectrum: 0.8820737777277827
typography_spectrum: 0.2336242003366351
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#0036c7'
    - '#898989'
    - '#fd0030'
  brandStrength: 0.125
  lightness: 0.9695074167102575
  saturation: 0.6420264486223459
  rhythmicContrast: 0.7839144943282008
purpose: []
